# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: CDESoftware.TBRAC-2024
PackageVersion: 06.03.0007
InstallerType: exe
InstallerSwitches:
  Silent: /exenoui /qn /norestart
Installers:
- Architecture: x86
  InstallerUrl: https://static.cdesoftware.com/tbrac2024/TBRAC2024INSTALLER.EXE
  InstallerSha256: d940748dea2bee0f0d8c72fcd50135d2711ba6c2b966adb0c2b7e6caec4511fa
ManifestType: installer
ManifestVersion: 1.9.0